### ISSUE TITLE
[Test Failure] Sync should continue if not all slaves dropped dual-channel-replication

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#1153]
Sync should continue if not all slaves dropped dual-channel-replication no in tests/integration/dual-channel-replication.tcl

https://github.com/valkey-io/valkey/actions/runs/11283922852/job/31417235703#step:5:7269

Doesn't specifically look like a dual channel issue, but seems to be a test issue.

**Comment by madolson** [comment]
https://github.com/valkey-io/valkey/actions/runs/11265007966/job/31326079613#step:5:7285

**Comment by madolson** [comment]
Another instance https://github.com/valkey-io/valkey/actions/runs/11300915465/job/31434518881#step:5:7278

**Comment by ranshid** [comment]
Seems the issue is related to the fact that without dual-channel the replication COB is filled up during the test, for example:
```
30566:M 11 Oct 2024 01:04:08.153 # Client id=6 addr=127.0.0.1:63067 laddr=127.0.0.1:21984 fd=16 name= age=48 idle=48 flags=S db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=15865 omem=268435800 tot-mem=268437720 events=r cmd=psync user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=241 tot-net-out=22 tot-cmds=5 scheduled to be closed ASAP for overcoming of output buffer limits.
```

I think of 2 fixes:
1. configure high COB limit for replica (256mb)
2. There are hard status checks for the number of sync/partial_sync_ok. in caes there will be some random disconnects during the test, it might terminate flaky. I think we might want to change the checks to '>' instead of '=='

@naglera WDYT?
