### ISSUE TITLE
ioredis -> iovalkey (Node.js client)

### ISSUE THREAD

**Issue by mcollina** [madolson/placeholderkv#329]
I've forked [ioredis](http://npm.im/ioredis) into [iovalkey](http://npm.im/iovalkey).

I'd love to move it to this org and/or maintain it under the org umbrella.

**Comment by madolson** [comment]
On top of we are still unsure about what we're doing about clients, I want to finalize our governance doc (which will include maintainership of sub-projects) before we accept any donations of projects. We shared a draft amongst the TSC. I was supposed to post the public PR on Monday but I haven't incorporated their feedback yet <_<.

I like the naming though.

**Comment by mcollina** [comment]
Let me know. I sincerely expect Redis 8 to break the protocol, making their clients only work with the official database. Elastic did the exact same move, and so far they seem to be following the same playbook.

**Comment by madolson** [comment]
So I suppose the consensus is we will take it and move it under our umbrella. One point I do want to ask about is we would prefer only taking one client per language, and I see there are two popular Redis clients (node-redis and ioredis). Is there much consensus about which one of those is better adopted or preferred by the community?

**Comment by PingXie** [comment]
I don't think we should set a limit on the number of clients per language. The client ecosystem is big and different clients can focus on different areas. For instance, some clients might optimize for performance while some others might have better support for observability. I think the key is "quality/reputation", which we could consider "outsourcing" to the community and rely on the community to keep us informed (so that we can also drop clients that are not longer maintained, for whatever reasons).

**Comment by PingXie** [comment]
On the flip side though, I can also see the (valid) argument that "why don't we consolidate the efforts into one official client and make it the best all around?" I just don't know if this is feasible given the diverse requirements out there. Curious to hear the community thoughts.

**Comment by zuiderkwast** [comment]
We have a decision that we will accept client forks under the valkey-io org. See https://github.com/orgs/valkey-io/discussions/362

Since we would prefer on one official client per language, the question is why not node-redis? Are the APIs and features very different and what are the main differences between ioredis and node-redis?

**Comment by mcollina** [comment]
Currently, `ioredis` is downloaded 5m per week, while `redis` is downloaded 3m weekly. 

Historically, ioredis was _better_. Now they are essentially on par. However, the `redis` one has a more complex codebase and it also support the proprietary features of redis.

If you plan to reimplement some of the non-oss add-ons, then possibly `redis` might make sense.

(I’m happy to help either way).

**Comment by zuiderkwast** [comment]
That's what I needed to hear. I'm convinced. :smile:

@valkey-io/core-team OK? If you agree, please :+1:, otherwise :-1:.

**Comment by mcollina** [comment]
moved!
