### ISSUE TITLE
[BUG] Duplicated arguments are accepted in ZINTER, ZUNION, and ZDIFF command

### ISSUE THREAD

**Issue by yyyhe** [madolson/placeholderkv#571]
**Describe the bug**

In the current command handler for ZINTER, ZUNION, and ZDIFF (or any command utilizing the 'zunionInterDiffGenericCommand' function), Valkey accepts duplicate argument inputs. The last argument provided will overwrite any previously provided arguments.

**To reproduce**
See the following example:
```
127.0.0.1:6379> zadd T 1 A 2 B
(integer) 2
127.0.0.1:6379> zadd G 2 B 3 C
(integer) 2
127.0.0.1:6379> zinter 2 T G WEIGHTS 1 2 WITHSCORES
1) "B"
2) "6"
127.0.0.1:6379> zinter 2 T G WEIGHTS 2 2 WITHSCORES
1) "B"
2) "8"
127.0.0.1:6379> zinter 2 T G WEIGHTS 1 2 WEIGHTS 2 2 WITHSCORES
1) "B"
2) "8"
127.0.0.1:6379> zinter 2 T G AGGREGATE SUM WITHSCORES
1) "B"
2) "4"
127.0.0.1:6379> zinter 2 T G AGGREGATE MIN WITHSCORES
1) "B"
2) "2"
127.0.0.1:6379> zinter 2 T G AGGREGATE MIN AGGREGATE SUM WITHSCORES
1) "B"
2) "4"
```

**Expected behavior**

To minimize confusion, the expected behavior is to return an error reply when duplicate arguments are provided.

**Additional information**

N/A.

**Comment by hwware** [comment]
@madolson do you think it is a bug?

**Comment by hpatro** [comment]
I think streams command argument parser is written in a similar manner, where the last argument is picked.

@yyyhe Is that an accidental behavior by the client/yourself of passing the same argument multiple times?

**Comment by madolson** [comment]
I think it's a minor bug, since we aren't conforming to the documented behavior. We had a very similar issue related to 'hello' in the past (you can pass 'auth' multiple times), which I think just low quality argument parsing. I think it's worth trying to clean an up the argument parsing in the next major version.

**Comment by soloestoy** [comment]
Here we have an interesting piece of history, which we have discussed many times in the past (I will not quote the issues from Redis here). There are two scenarios:

1. For conflicting or semantically opposite arguments, Valkey rejects such usage, for example, `SET key value xx nx` would directly return an error.

2. As for arguments of the same type, Valkey currently adopts a 'last win' strategy.

The core issue here is the second point, regarding the same arguments. Honestly, I'm not a fan of the 'last win' strategy, it's not a good usage pattern (I suspect that initially using multiple arguments might have likely been a user error). But indeed, there are quite a few users who use it this way. Although we have the opportunity to make some breaking changes in the next major version, we need to be very cautious, because this kind of usage is hard for users to detect themselves and it's difficult to carry out a comprehensive check before upgrading to a major version, which can lead to crash after the upgrade.

**Comment by hpatro** [comment]
@Shivshankar-Reddy has a PR #667, I think we should first finalize if we want to introduce this breaking change and then think through how to build a maintainable solution.

@valkey-io/core-team Could we do the voting thing?

:+1: = fix the bug and return syntax error for duplicated arguments
:-1: = keep current behaviour

**Comment by zuiderkwast** [comment]
I think it's safer to keep the existing behaviour. Fixing it can break some (badly written) application code. I've already seen minor fixes that seem safe, but still break things, like #759 broke the test suites in multiple projects, including hiredis-cluster, libvalkey cluster.

We can adjust the documentation instead. We don't need to say "last write wins", but we can just say that it's undefined which of the duplicated argument will be used, so users shouldn't do this.

**Comment by madolson** [comment]
We need to add some form of documentation that multiple arguments are accepted, but leave it undefined what the behavior is.

**Comment by zuiderkwast** [comment]
The decision is to keep the current behaviour. Thanks anyway.

If it would be a new command, I think we all agree that it's better to return an error for duplicates, but this is old and the risk of breaking some client applications is a worse problem.
