### ISSUE TITLE
[BUG] Example ACL for sentinel does not work

### ISSUE THREAD

**Issue by utdrmac** [madolson/placeholderkv#744]
**Describe the bug**
https://github.com/valkey-io/valkey/blob/unstable/sentinel.conf#L122
This example of a minimal user account in your Valkey server for Sentinel is incorrect. If you add this ACL as-is to your valkey users.acl, valkey will add `resetchannels -@all` before the +client which prevents sentinel from publishing messages to the `__sentinel__:hello` pubsub for sentinel discovery.

**To reproduce**
Copy the example from conf to valkey server. start valkey server. observe change in ACL. attempt to start sentinel using ACL.

**Expected behavior**
I expected the minimal example to work properly.

**Additional information**
Simply adding `&__sentinel__:hello` before +client in the example should allow the example to work properly.

**Comment by hwware** [comment]
I will check it, Thanks. Any update I will let you know

**Comment by hpatro** [comment]
Thanks for highlighting the issue @utdrmac .

The default permission around channels used to be `allchannels`. However, to improve the security posture by default we updated it to `resetchannels` since 7.2. Hence, the issue happens which you described above.

I think we can update the `sentinel.conf` acl user to make setup simpler. We could maybe have the user with `&__sentinel__:*` (note: I don't have lot of Sentinel context, hence suggesting a generic channel pattern)

**Comment by hpatro** [comment]
Just looked at the codebase, it's restrictive to `__sentinel__:hello`.
