### ISSUE TITLE
Update rioconnwrite size from https://github.com/valkey-io/valkey/pull/60

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#796]
1024 seems too small and we will end up with high syscall overhead. Also I would imagine that the majority case will be one connection (one replica going through full sync) only. Is there any experimental data that shows 1024 is indeed better?

I would suggest writing at least 16KB or 64KB a piece.

_Originally posted by @PingXie in https://github.com/valkey-io/valkey/pull/60#discussion_r1660463682_

**Comment by madolson** [comment]
@ranshid Going to assign this to you and you go poke Amit.

**Comment by ranshid** [comment]
>Also I would imagine that the majority case will be one connection (one replica going through full sync) only.

I agree that this is the common scenario, although we should be careful not to cause high degradation of the multiple replicas QoS.

> would suggest writing at least 16KB or 64KB a piece.

So I think that for the TLS case 16K does sound like a good candidate since the max fragment is USUALLY 16K size (there are extensions which allows setting it smaller, but we do not use them). In our external tests in AWS we did observe some sweet point of 8K, and I would imagine that fact that the max path MTU is 9001 would also support such sizes.

In fact I did write a simple test program and did not observe any significant improvement in read/write going with chunks bigger than 4K. What I could notice is that the CPU consumption using normal TCP stream Is reduced as the chunk size is bigger, and with TLS is optimal at ~16K (which is expected as the TLS frame size max at 16K)

**Test**
[test-program.zip](https://github.com/user-attachments/files/16332446/test-program.zip)
Include client/server implementations for client sending 100MB data to a server. the tests are both in TLS and TCP.
I run the tests on separate m5.xlarge EC2 instances on AWS. 
the executables were compiled and run on ubuntu:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```

```
uname -a
Linux ip-172-31-22-140 6.8.0-1009-aws #9-Ubuntu SMP Fri May 17 14:39:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
All files were compiled with O3 optimization level.
```
gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
```


**Results:**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ranshid/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ranshid/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Chunk Size | write-time sec | writes total | write cpu-time (usr+sys) | read-time sec | read total syscalls | read cpu-time (usr+sys)
-- | -- | -- | -- | -- | -- | --
1K | 0.162946 | 102400 | 0.185916 | 0.168479 | 2447 | 0.026945
4K | 0.163036 | 25600 | 0.122629 | 0.168627 | 715 | 0.023382
8K | 0.163942 | 12800 | 0.121131 | 0.168887 | 704 | 0.039388
16K | 0.163614 | 6400 | 0.104742 | 0.168202 | 2483 | 0.025574
64K | 0.16279 | 1600 | 0.098792 | 0.168854 | 1068 | 0.046929
1K - TLS | 0.32648 | 102400 | 0.366961 | 0.330785 | 102400 | 0.337377
4K - TLS | 0.164296 | 25600 | 0.183326 | 0.169032 | 25600 | 0.129952
8K - TLS | 0.163977 | 12800 | 0.163118 | 0.169484 | 12800 | 0.098432
16K - TLS | 0.164861 | 6400 | 0.150666 | 0.169878 | 6383 | 0.094794
64K - TLS | 0.163704 | 6400 | 0.156125 | 0.169323 | 6388 | 0.089971



</body>

</html>



Note that the CPU times are for the entire process run and not just the read/write part.


I think that given all that 4K would probably be enough, however given that AWS already have some milage with 8K buffer size which would potentially reduce the number of reads on the replica side I would suggest to go with 8K.

**Comment by touitou-dan** [comment]
Is it possible that the 0.16 sec lower bound is due the  single TCP connection bw limit (100MB/4gbs == 0.2s)?  If this is the case you may want to profile the sender (in case of plain TCP) and the receiver (in case of TLS)

**Comment by ranshid** [comment]
> Is it possible that the 0.16 sec lower bound is due the single TCP connection bw limit (100MB/4gbs == 0.2s)? If this is the case you may want to profile the sender (in case of plain TCP) and the receiver (in case of TLS)

I think that is a good point @touitou-dan. I think the flow limit is 5GB (but removing the ip and protocol headers would probably bring the limit you suggested)
BTW isn't 100MB/4gbs = 0.02s?

**Comment by ranshid** [comment]
I updated the stats with CPU measurements. Now it makes much more sense with being more optimal at 16K (with TLS). I will change the PR to max at 16K chunks and see what other people think.
